version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules/
      - ./server:/app
    environment:
      - NODEPORT=5000
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDB=blogster
      - MYSQLUSER=mysql
      - MYSQLPASSWORD=mysqlpassword
    ports:
      - '5000:5000'
    command: sh start.sh
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysqlpassword
      - MYSQL_DATABASE=blogster
    volumes:
      - ./docker/data:/var/lib/mysql
    ports:
      - 3306:3306
